"""纯程序化地形引擎。

引擎只负责把类型化配方计算为标量场，不了解 Minecraft 方块、区域、
raster manifest 或 Bong server 的具体实现。
"""

from .climate import (
    CLIMATE_PALETTE,
    CLIMATE_SURFACE_PALETTE,
    CLIMATE_TRANSITION_PALETTE,
    ClimateAxis,
    ClimateBand,
    ClimateField,
    ClimateKind,
    ClimateSurfaceFamily,
    ClimateTransition,
    ClimateWorldBounds,
    GlobalClimatePlan,
    sample_climate,
)
from .constants import CAVE_RARITY_MULTIPLIERS, DEFAULT_RIVERBED_MATERIALS, MOUNTAIN_ROCK_PALETTE
from .generated_world import Heightfield
from .hydraulic import HydraulicErosionResult, apply_hydraulic_erosion
from .glaciers import (
    GLACIAL_COVER_PALETTE,
    GLACIAL_CREVASSE_PALETTE,
    GLACIAL_LANDFORM_PALETTE,
    GLACIAL_SURFACE_PALETTE,
    PERMAFROST_PALETTE,
    GlacialFlowPlan,
    GlacierValleyField,
    GlacialMassBalanceField,
    WindSnowField,
    apply_glaciers,
    permafrost_surface_materials,
    sample_glacial_mass_balance,
    sample_glacial_crevasses,
    sample_glacier_valley_field,
    sample_wind_snow_field,
    surface_wind_normal_alignment,
    plan_glacial_flow,
    generate_snow_mountain_resource_blocks,
)
from .pipeline import generate_heightfield
from .settlement_points import (
    SettlementInterestPoint,
    SettlementSpawnArea,
    settlement_interest_point_manifest,
    settlement_spawn_area_manifest,
)
from .mountains import (
    MOUNTAIN_SURFACE_PALETTE,
    MountainMaterialField,
    apply_mountains_with_uplift,
    mountain_surface_materials,
    sample_mountain_material_field,
)
from .surface import BASE_SURFACE_PALETTE, build_visible_surface_layer
from .town import (
    SettlementBlock,
    SettlementGeneration,
    generate_town,
    generate_town_result,
)
from .standalone_structures import (
    StandaloneStructureGeneration,
    generate_standalone_structures,
)
from .terrain_config import (
    Basin,
    Canyon,
    GlacialSystem,
    HydraulicErosionSettings,
    MountainMaterialSettings,
    MountainRange,
    NaturalRelief,
    NoiseLayer,
    Point,
    RidgedMultifractal,
    River,
    SnowMountainResourceSpec,
    SpawnPlainSettings,
    TownSettings,
    StandaloneStructureSettings,
    ValleySystem,
)
from .valleys import (
    ValleyErosionPlan,
    ValleyField,
    apply_valley_erosion,
    apply_watershed_divide,
    plan_valley_erosion,
    sample_valley_fields,
    watershed_divide_strength,
)
from .underground_config import (
    CaveNetwork,
    SolidOreSpec,
    UndergroundBlock,
    UndergroundRiverNetwork,
    UndergroundWaterBlock,
)
from .world_config import TerrainRecipe

__all__ = [
    "Basin",
    "Canyon",
    "CaveNetwork",
    "CAVE_RARITY_MULTIPLIERS",
    "CLIMATE_PALETTE",
    "CLIMATE_SURFACE_PALETTE",
    "CLIMATE_TRANSITION_PALETTE",
    "ClimateAxis",
    "ClimateBand",
    "ClimateField",
    "ClimateKind",
    "ClimateSurfaceFamily",
    "ClimateTransition",
    "ClimateWorldBounds",
    "DEFAULT_RIVERBED_MATERIALS",
    "MOUNTAIN_ROCK_PALETTE",
    "GlacialSystem",
    "GLACIAL_COVER_PALETTE",
    "GLACIAL_CREVASSE_PALETTE",
    "GLACIAL_LANDFORM_PALETTE",
    "GLACIAL_SURFACE_PALETTE",
    "PERMAFROST_PALETTE",
    "GlacialMassBalanceField",
    "WindSnowField",
    "GlacialFlowPlan",
    "GlacierValleyField",
    "GlobalClimatePlan",
    "Heightfield",
    "HydraulicErosionResult",
    "HydraulicErosionSettings",
    "apply_hydraulic_erosion",
    "MountainRange",
    "MountainMaterialSettings",
    "MOUNTAIN_SURFACE_PALETTE",
    "MountainMaterialField",
    "NaturalRelief",
    "NoiseLayer",
    "Point",
    "RidgedMultifractal",
    "River",
    "SnowMountainResourceSpec",
    "SpawnPlainSettings",
    "TownSettings",
    "StandaloneStructureGeneration",
    "StandaloneStructureSettings",
    "SettlementBlock",
    "SettlementGeneration",
    "SettlementInterestPoint",
    "SettlementSpawnArea",
    "SolidOreSpec",
    "TerrainRecipe",
    "UndergroundBlock",
    "UndergroundWaterBlock",
    "UndergroundRiverNetwork",
    "ValleySystem",
    "ValleyErosionPlan",
    "ValleyField",
    "apply_valley_erosion",
    "apply_watershed_divide",
    "plan_valley_erosion",
    "sample_valley_fields",
    "watershed_divide_strength",
    "apply_glaciers",
    "permafrost_surface_materials",
    "sample_glacial_mass_balance",
    "sample_glacial_crevasses",
    "generate_snow_mountain_resource_blocks",
    "sample_glacier_valley_field",
    "sample_wind_snow_field",
    "surface_wind_normal_alignment",
    "plan_glacial_flow",
    "generate_heightfield",
    "generate_town",
    "generate_town_result",
    "settlement_interest_point_manifest",
    "generate_standalone_structures",
    "settlement_spawn_area_manifest",
    "apply_mountains_with_uplift",
    "mountain_surface_materials",
    "sample_mountain_material_field",
    "BASE_SURFACE_PALETTE",
    "build_visible_surface_layer",
    "sample_climate",
]
