"""Export a complete standalone world for the existing Three.js console."""

from __future__ import annotations

import json
import math
from pathlib import Path

from .adapters import to_bong_tile, write_bong_raster
from .data.recipes import DEFAULT_RECIPE
from .engine import TerrainRecipe, generate_heightfield


SPAN_ENCODING = {
    "max_spans": 4,
    "bytes_per_column": 16,
    "sentinel": 32767,
    "count_file": "spans_count.bin",
    "spans_file": "spans.bin",
    "slot_layout": "i16_le(floor_y, ceiling_y) x max_spans, unused slots = sentinel",
}


def _tile_range(minimum: int, maximum: int, tile_size: int) -> range:
    first = math.floor(minimum / tile_size)
    last = math.floor(maximum / tile_size)
    return range(first, last + 1)


def export_preview_world(
    output_dir: Path,
    *,
    recipe: TerrainRecipe = DEFAULT_RECIPE,
    seed: int = 812731,
    min_x: int = -4096,
    max_x: int = 4095,
    min_z: int = -4096,
    max_z: int = 4095,
    tile_size: int = 256,
) -> Path:
    """Generate every tile in a bounded world and return its manifest path."""

    if tile_size < 1 or tile_size & (tile_size - 1):
        raise ValueError("tile_size must be a positive power of two")
    if min_x > max_x or min_z > max_z:
        raise ValueError("world bounds must be ordered")
    rasters_dir = output_dir / "rasters"
    rasters_dir.mkdir(parents=True, exist_ok=True)
    tile_entries: list[dict[str, object]] = []

    for tile_z in _tile_range(min_z, max_z, tile_size):
        for tile_x in _tile_range(min_x, max_x, tile_size):
            origin_x = tile_x * tile_size
            origin_z = tile_z * tile_size
            field = generate_heightfield(
                recipe,
                width=tile_size,
                height=tile_size,
                seed=seed,
                origin_x=origin_x,
                origin_z=origin_z,
            )
            tile = to_bong_tile(field, sea_level=recipe.sea_level)
            write_bong_raster(
                tile,
                rasters_dir,
                tile_x=tile_x,
                tile_z=tile_z,
                world_name=recipe.name,
                write_manifest=False,
            )
            tile_entries.append(
                {
                    "tile_x": tile_x,
                    "tile_z": tile_z,
                    "dir": f"tile_{tile_x}_{tile_z}",
                    "zones": ["procedural_world"],
                    "layers": [
                        "surface_id",
                        "subsurface_id",
                        "water_level",
                        "biome_id",
                        "feature_mask",
                        "boundary_weight",
                    ],
                    "spans": True,
                }
            )

    manifest = {
        "version": 2,
        "backend": "raster",
        "world_name": recipe.name,
        "tile_size": tile_size,
        "spans_encoding": SPAN_ENCODING,
        "world_bounds": {
            "min_x": min_x,
            "max_x": max_x,
            "min_z": min_z,
            "max_z": max_z,
        },
        "surface_palette": ["stone", "coarse_dirt", "gravel", "grass_block"],
        "biome_palette": ["minecraft:plains", "minecraft:river"],
        "tiles": tile_entries,
        "pois": [],
        "poi_connections": [],
        "zones": [
            {
                "name": "procedural_world",
                "display_name": "程序山河",
                "terrain_profile": recipe.name,
                "spirit_qi": 0.35,
                "danger_level": 2,
                "worldgen": {"generator": "bong_worldgen", "seed": seed},
            }
        ],
        "semantic_layers": [],
        "vertical_layers": [],
        "notes": [
            "Generated by standalone BongWorldGen.",
            "The existing Three.js console reads this manifest directly.",
        ],
    }
    manifest_path = rasters_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return manifest_path


__all__ = ["SPAN_ENCODING", "export_preview_world"]
